title: HatSploit Documentation
description: HatSploit Documentation
theme: just-the-docs

url: https://docs.hatsploit.com

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
